<? include "header.phtml"; ?>
  <h1><?=$this->escape($this->title);?></h1>
  <h2><?=$this->escape($this->description);?></h2>
  <a href="register">Register</a>
  <table border="1">
    <tr>
	  <th>ID</th>
	  <th>User Name</th>	  
	  <th>Email</th>	  
	  <th>Action</th>	  
	</tr>
  <? $datas = $this->datas;
     foreach($datas as $i){ ?>
    <tr>
	  <td><?=$i['id']?></td>	
	  <td><?=$i['username']?></td>
	  <td><?=$i['email']?></td>	    
	  <td>
	    <a href="edit/id/<?=$i['id']?>">Edit</a>
		|
	    <a href="del/id/<?=$i['id']?>">Delete</a>		
	  </td>	  
	</tr> 
  <? } ?>
  </table>
  
<? include "footer.phtml"; ?>